### ISSUE TITLE
Make "sort-imports" plugin work with typescript files.

### ISSUE THREAD

**Issue by SimonVanneste** [Azumuta/eslint-plugin-azumuta#12]
```
cobalt-core % npx eslint ./ui/Balance/peripheral/peripheralConnectionPool.ts
```
```
TypeError: context.getFilename is not a function
Occurred while linting /Users/simonvanneste/azumuta/cobalt-core/ui/Balance/peripheral/peripheralConnectionPool.ts:35
    at getContextPackagePath (/Users/simonvanneste/azumuta/node_modules/eslint-plugin-import/lib/core/packagePath.js:15:410)
    at typeTest (/Users/simonvanneste/azumuta/node_modules/eslint-plugin-import/lib/core/importType.js:109:2291)
    at resolveImportType (/Users/simonvanneste/azumuta/node_modules/eslint-plugin-import/lib/core/importType.js:109:2724)
    at catchAll (/Users/simonvanneste/azumuta/node_modules/eslint-plugin-azumuta/lib/rules/sort-imports.js:44:44)
    at /Users/simonvanneste/azumuta/node_modules/eslint-plugin-azumuta/lib/rules/sort-imports.js:74:35
    at Array.find (<anonymous>)
    at /Users/simonvanneste/azumuta/node_modules/eslint-plugin-azumuta/lib/rules/sort-imports.js:74:20
    at Array.map (<anonymous>)
    at orderImports (/Users/simonvanneste/azumuta/node_modules/eslint-plugin-azumuta/lib/rules/sort-imports.js:73:38)
    at importsDone (/Users/simonvanneste/azumuta/node_modules/eslint-plugin-azumuta/lib/rules/sort-imports.js:122:31)
```

**Comment by skluyskens-azumuta** [comment]
Added context, created PR
